<#
Prerequisites
- Windows 11
- PowerShell 5.1+
- Node toolchain installed (Node + pnpm recommended)

Usage
  powershell -File .\new-node-project-windows.ps1 -Help
  powershell -File .\new-node-project-windows.ps1 -Name demo-node
  powershell -File .\new-node-project-windows.ps1 -Name demo-node -BaseDir D:\dev\projects

Generates
- README.md + Quick Start
- project_config.yaml
- package.json
- src\index.js
- scripts\dev.ps1, run.ps1, test.ps1
- .gitignore

Logs/State
- Logs : D:\aryan-setup\logs\new-node-project-windows.log
- State: D:\aryan-setup\state\new-node-project-windows.state.json
#>

[CmdletBinding()]
param(
  [switch]$Help,
  [Parameter(Mandatory=$false)] [string]$Name,
  [Parameter(Mandatory=$false)] [string]$BaseDir = "D:\dev\projects"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-ISTTimestamp {
  $tz = [TimeZoneInfo]::FindSystemTimeZoneById("India Standard Time")
  $nowIst = [TimeZoneInfo]::ConvertTime([DateTime]::Now, $tz)
  return "IST " + $nowIst.ToString("dd-MM-yyyy HH:mm:ss")
}

function Write-Log {
  param([ValidateSet("Error","Warning","Info","Debug")] [string]$Level, [string]$Message)
  $line = "$(Get-ISTTimestamp) $Level $Message"
  Add-Content -Path $script:LogFile -Value $line -Encoding UTF8
  Write-Host $line
}

function Ensure-Dir([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path)) { New-Item -ItemType Directory -Path $Path -Force | Out-Null }
}

function Write-IfMissing([string]$Path, [string]$Content, [string]$Encoding="utf8") {
  if (Test-Path -LiteralPath $Path) {
    Write-Log -Level Debug -Message "Exists, not overwriting: $Path"
    return
  }
  Ensure-Dir (Split-Path -Parent $Path)
  Set-Content -Path $Path -Value $Content -Encoding $Encoding
  Write-Log -Level Info -Message "Created: $Path"
}

function Save-State([hashtable]$State) {
  $json = $State | ConvertTo-Json -Depth 8
  Set-Content -Path $script:StateFile -Value $json -Encoding UTF8
}

function Show-Help {
@"
new-node-project-windows.ps1

Usage:
  powershell -File .\new-node-project-windows.ps1 -Name <project> [-BaseDir <dir>]
"@ | Write-Host
}

if ($Help) { Show-Help; exit 0 }
if (-not $Name) { throw "Missing -Name. Use -Help for usage." }
if ($Name -notmatch '^[a-zA-Z0-9._-]+$') { throw "Invalid -Name '$Name' (use letters/digits/dot/underscore/hyphen)" }

$LogRoot   = "D:\aryan-setup\logs"
$StateRoot = "D:\aryan-setup\state"
Ensure-Dir $LogRoot
Ensure-Dir $StateRoot
$script:LogFile   = Join-Path $LogRoot "new-node-project-windows.log"
$script:StateFile = Join-Path $StateRoot "new-node-project-windows.state.json"

Write-Log -Level Info -Message "=== START new-node-project-windows (Name=$Name BaseDir=$BaseDir) ==="

Ensure-Dir $BaseDir
$ProjectDir = Join-Path $BaseDir $Name
Ensure-Dir $ProjectDir

$existing = Get-ChildItem -LiteralPath $ProjectDir -Force -ErrorAction SilentlyContinue
if ($existing.Count -gt 0) {
  Write-Log -Level Warning -Message "Project dir exists and is not empty: $ProjectDir"
  Write-Log -Level Warning -Message "Idempotent mode: only missing files will be created (no overwrites)."
}

Ensure-Dir (Join-Path $ProjectDir "src")
Ensure-Dir (Join-Path $ProjectDir "scripts")

$TemplateVersion = "1.0.0"
$CreatedAt = Get-ISTTimestamp

Write-IfMissing (Join-Path $ProjectDir ".gitignore") @"
node_modules/
dist/
build/
.env
.DS_Store
"@

Write-IfMissing (Join-Path $ProjectDir "package.json") @"
{
  "name": "$Name",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "node .\\src\\index.js",
    "start": "node .\\src\\index.js",
    "test": "echo \"No tests yet\" && exit 0"
  }
}
"@

Write-IfMissing (Join-Path $ProjectDir "src\index.js") "console.log('Hello from $Name!');`r`n"

Write-IfMissing (Join-Path $ProjectDir "scripts\run.ps1") @"
<#
Usage:
  powershell -File .\scripts\run.ps1

First time:
  pnpm install
#>
pnpm -s run start
"@

Write-IfMissing (Join-Path $ProjectDir "scripts\dev.ps1") @"
<#
Usage:
  powershell -File .\scripts\dev.ps1

First time:
  pnpm install
#>
pnpm -s run dev
"@

Write-IfMissing (Join-Path $ProjectDir "scripts\test.ps1") @"
<#
Usage:
  powershell -File .\scripts\test.ps1
#>
pnpm -s run test
"@

Write-IfMissing (Join-Path $ProjectDir "project_config.yaml") @"
project:
  name: "$Name"
  type: "node"
  created_at: "$CreatedAt"
  template_version: "$TemplateVersion"

node:
  toolchain: "node+pnpm"
  caches:
    pnpm_store_dir: "D:\dev\cache\pnpm-store"
    npm_cache_dir: "D:\dev\cache\npm-cache"
"@

Write-IfMissing (Join-Path $ProjectDir "README.md") @"
# $Name

This project was generated by **setup-aryan** on Windows.

## Quick Start (Windows)

```powershell
pnpm install
pnpm run dev
````

## What got generated

* `project_config.yaml`: toolchain + cache expectations
* `package.json`: minimal scripts
* `src\index.js`: runnable entrypoint
* `scripts\*.ps1`: helper runners

## Notes on disk usage (pnpm)

pnpm uses a global store (hard-links where possible) to prevent `node_modules` duplication.
"@

Save-State @{
status     = "ok"
project_dir= $ProjectDir
at         = (Get-ISTTimestamp)
}

Write-Log -Level Info -Message "=== DONE new-node-project-windows ==="
Write-Log -Level Info -Message "Project: $ProjectDir"
exit 0