<#
Prerequisites
- Windows 11
- PowerShell 5.1+
- Python toolchain installed (Miniconda + uv recommended)
- D:\dev exists (or script will create it)

Usage
  powershell -File .\new-python-project-windows.ps1 -Help
  powershell -File .\new-python-project-windows.ps1 -Name demo-ml -Ai
  powershell -File .\new-python-project-windows.ps1 -Name demo-py -BaseDir D:\dev\projects

What it generates
- README.md + Quick Start
- project_config.yaml
- pyproject.toml
- requirements.txt
- src\main.py
- scripts\run.ps1, dev.ps1, test.ps1, lint.ps1
- .gitignore

Logging / State
- Logs : D:\aryan-setup\logs\new-python-project-windows.log
- State: D:\aryan-setup\state\new-python-project-windows.state.json
#>

[CmdletBinding()]
param(
  [switch]$Help,
  [Parameter(Mandatory=$false)] [string]$Name,
  [Parameter(Mandatory=$false)] [string]$BaseDir = "D:\dev\projects",
  [switch]$Ai
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-ISTTimestamp {
  $tz = [TimeZoneInfo]::FindSystemTimeZoneById("India Standard Time")
  $nowIst = [TimeZoneInfo]::ConvertTime([DateTime]::Now, $tz)
  return "IST " + $nowIst.ToString("dd-MM-yyyy HH:mm:ss")
}

function Write-Log {
  param(
    [ValidateSet("Error","Warning","Info","Debug")] [string]$Level,
    [string]$Message
  )
  $line = "$(Get-ISTTimestamp) $Level $Message"
  Add-Content -Path $script:LogFile -Value $line -Encoding UTF8
  Write-Host $line
}

function Ensure-Dir([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path -Force | Out-Null
  }
}

function Write-IfMissing([string]$Path, [string]$Content, [string]$Encoding="utf8") {
  if (Test-Path -LiteralPath $Path) {
    Write-Log -Level Debug -Message "Exists, not overwriting: $Path"
    return
  }
  Ensure-Dir (Split-Path -Parent $Path)
  Set-Content -Path $Path -Value $Content -Encoding $Encoding
  Write-Log -Level Info -Message "Created: $Path"
}

function Append-IfMissing([string]$Path, [string]$Marker, [string]$Block) {
  if (-not (Test-Path -LiteralPath $Path)) { return }
  $txt = Get-Content -LiteralPath $Path -Raw -ErrorAction SilentlyContinue
  if ($txt -and $txt.Contains($Marker)) { return }
  Add-Content -Path $Path -Value "`r`n$Block" -Encoding UTF8
  Write-Log -Level Info -Message "Appended block to: $Path"
}

function Save-State([hashtable]$State) {
  $json = $State | ConvertTo-Json -Depth 8
  Set-Content -Path $script:StateFile -Value $json -Encoding UTF8
}

function Show-Help {
@"
new-python-project-windows.ps1

Usage:
  powershell -File .\new-python-project-windows.ps1 -Name <project> [-BaseDir <dir>] [-Ai]
  powershell -File .\new-python-project-windows.ps1 -Help

Creates a complete Python starter kit (conda + uv workflow).
"@ | Write-Host
}

if ($Help) { Show-Help; exit 0 }
if (-not $Name) { throw "Missing -Name. Use -Help for usage." }
if ($Name -notmatch '^[a-zA-Z0-9._-]+$') { throw "Invalid -Name '$Name' (use letters/digits/dot/underscore/hyphen)" }

# Logs/state
$LogRoot   = "D:\aryan-setup\logs"
$StateRoot = "D:\aryan-setup\state"
Ensure-Dir $LogRoot
Ensure-Dir $StateRoot
$script:LogFile   = Join-Path $LogRoot "new-python-project-windows.log"
$script:StateFile = Join-Path $StateRoot "new-python-project-windows.state.json"

Write-Log -Level Info -Message "=== START new-python-project-windows (Name=$Name BaseDir=$BaseDir Ai=$Ai) ==="

Ensure-Dir $BaseDir
$ProjectDir = Join-Path $BaseDir $Name
Ensure-Dir $ProjectDir

# Idempotent: do not overwrite existing content
$existing = Get-ChildItem -LiteralPath $ProjectDir -Force -ErrorAction SilentlyContinue
if ($existing.Count -gt 0) {
  Write-Log -Level Warning -Message "Project dir exists and is not empty: $ProjectDir"
  Write-Log -Level Warning -Message "Idempotent mode: only missing files will be created (no overwrites)."
}

Ensure-Dir (Join-Path $ProjectDir "src")
Ensure-Dir (Join-Path $ProjectDir "scripts")

$TemplateVersion = "1.0.0"
$CreatedAt = Get-ISTTimestamp

Write-IfMissing (Join-Path $ProjectDir ".gitignore") @"
.venv/
__pycache__/
*.pyc
.pytest_cache/
.coverage
dist/
build/
*.egg-info/
.env
.DS_Store
"@

Write-IfMissing (Join-Path $ProjectDir "requirements.txt") @"
# Add your Python deps here (pip-style), then run:
#   uv pip install -r requirements.txt
"@

Write-IfMissing (Join-Path $ProjectDir "pyproject.toml") @"
[project]
name = "$Name"
version = "0.1.0"
description = "$Name (generated by setup-aryan)"
readme = "README.md"
requires-python = ">=3.11"

[tool.uv]
# Let conda own the interpreter; uv owns pip installs.
"@

Write-IfMissing (Join-Path $ProjectDir "src\main.py") @"
def main() -> None:
    print("Hello from $Name!")
    print("If this is an AI/ML project, activate your conda env and install deps via uv.")

if __name__ == "__main__":
    main()
"@

Write-IfMissing (Join-Path $ProjectDir "scripts\run.ps1") @"
<#
Usage:
  powershell -File .\scripts\run.ps1
#>
python .\src\main.py
"@

Write-IfMissing (Join-Path $ProjectDir "scripts\dev.ps1") @"
<#
Usage:
  powershell -File .\scripts\dev.ps1

Notes (conda + uv):
  conda activate <env>
  uv pip install -r requirements.txt
#>
powershell -File .\scripts\run.ps1
"@

Write-IfMissing (Join-Path $ProjectDir "scripts\test.ps1") @"
<#
Usage:
  powershell -File .\scripts\test.ps1
#>
Write-Host "No tests configured yet."
exit 0
"@

Write-IfMissing (Join-Path $ProjectDir "scripts\lint.ps1") @"
<#
Usage:
  powershell -File .\scripts\lint.ps1

Tip:
  uv pip install ruff black
  ruff check .
  black --check .
#>
Write-Host "No lint configured yet."
exit 0
"@

# project_config.yaml
$AiEnabled = if ($Ai) { "true" } else { "false" }

Write-IfMissing (Join-Path $ProjectDir "project_config.yaml") @"
project:
  name: "$Name"
  type: "python"
  created_at: "$CreatedAt"
  template_version: "$TemplateVersion"

python:
  toolchain: "conda+uv"
  caches:
    uv_cache_dir: "D:\dev\cache\uv"
    conda_pkgs_dir: "D:\dev\cache\conda\pkgs"
    conda_envs_dir: "D:\dev\envs\conda\envs"

ai_ml:
  enabled: $AiEnabled
"@

# README.md
$Readme = @"
# $Name

This project was generated by **setup-aryan** on Windows.

## Quick Start (Windows)

### 1) Create and activate conda env
Example env name: \`$Name-py\`

```powershell
conda create -n $Name-py python=3.11 -y
conda activate $Name-py
````

### 2) Install deps with uv (inside the active conda env)

```powershell
uv pip install -r requirements.txt
```

### 3) Run

```powershell
powershell -File .\scripts\run.ps1
```

## What got generated

* `project_config.yaml`: toolchain + cache expectations
* `requirements.txt`: add deps here
* `src\main.py`: runnable entrypoint
* `scripts\*.ps1`: helper runners

## Notes on disk usage (conda + uv)

Keep projects under `D:\dev\projects` and caches under `D:\dev\cache`.

uv keeps a global cache and hard-links where possible to reduce duplication.
"@

Write-IfMissing (Join-Path $ProjectDir "README.md") $Readme

if ($Ai) {
Append-IfMissing (Join-Path $ProjectDir "README.md") "## AI/ML Notes (Windows GPU)" @"

## AI/ML Notes (Windows GPU)

* For GUI apps, Windows typically uses iGPU by default unless you override Graphics settings.
* For ML training, you’ll usually run workloads that explicitly use CUDA (NVIDIA) when available.
  "@
  }

Save-State @{
status     = "ok"
project_dir= $ProjectDir
ai_mode    = [bool]$Ai
at         = (Get-ISTTimestamp)
}

Write-Log -Level Info -Message "=== DONE new-python-project-windows ==="
Write-Log -Level Info -Message "Project: $ProjectDir"
exit 0