<#
Prerequisites
- Windows 11
- PowerShell 5.1+
- JDK installed and javac/java available on PATH (Temurin 21 recommended)

Usage
  powershell -File .\new-java-project-windows.ps1 -Help
  powershell -File .\new-java-project-windows.ps1 -Name demo-java
  powershell -File .\new-java-project-windows.ps1 -Name demo-java -BaseDir D:\dev\projects

Generates (no Maven/Gradle dependency)
- README.md + Quick Start
- project_config.yaml
- src\Main.java
- scripts\build.ps1, run.ps1, clean.ps1
- .gitignore

Logs/State
- Logs : D:\aryan-setup\logs\new-java-project-windows.log
- State: D:\aryan-setup\state\new-java-project-windows.state.json
#>

[CmdletBinding()]
param(
  [switch]$Help,
  [Parameter(Mandatory=$false)] [string]$Name,
  [Parameter(Mandatory=$false)] [string]$BaseDir = "D:\dev\projects"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-ISTTimestamp {
  $tz = [TimeZoneInfo]::FindSystemTimeZoneById("India Standard Time")
  $nowIst = [TimeZoneInfo]::ConvertTime([DateTime]::Now, $tz)
  return "IST " + $nowIst.ToString("dd-MM-yyyy HH:mm:ss")
}

function Write-Log {
  param([ValidateSet("Error","Warning","Info","Debug")] [string]$Level, [string]$Message)
  $line = "$(Get-ISTTimestamp) $Level $Message"
  Add-Content -Path $script:LogFile -Value $line -Encoding UTF8
  Write-Host $line
}

function Ensure-Dir([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path)) { New-Item -ItemType Directory -Path $Path -Force | Out-Null }
}

function Write-IfMissing([string]$Path, [string]$Content, [string]$Encoding="utf8") {
  if (Test-Path -LiteralPath $Path) {
    Write-Log -Level Debug -Message "Exists, not overwriting: $Path"
    return
  }
  Ensure-Dir (Split-Path -Parent $Path)
  Set-Content -Path $Path -Value $Content -Encoding $Encoding
  Write-Log -Level Info -Message "Created: $Path"
}

function Save-State([hashtable]$State) {
  $json = $State | ConvertTo-Json -Depth 8
  Set-Content -Path $script:StateFile -Value $json -Encoding UTF8
}

function Show-Help {
@"
new-java-project-windows.ps1

Usage:
  powershell -File .\new-java-project-windows.ps1 -Name <project> [-BaseDir <dir>]
"@ | Write-Host
}

if ($Help) { Show-Help; exit 0 }
if (-not $Name) { throw "Missing -Name. Use -Help for usage." }
if ($Name -notmatch '^[a-zA-Z0-9._-]+$') { throw "Invalid -Name '$Name' (use letters/digits/dot/underscore/hyphen)" }

$LogRoot   = "D:\aryan-setup\logs"
$StateRoot = "D:\aryan-setup\state"
Ensure-Dir $LogRoot
Ensure-Dir $StateRoot
$script:LogFile   = Join-Path $LogRoot "new-java-project-windows.log"
$script:StateFile = Join-Path $StateRoot "new-java-project-windows.state.json"

Write-Log -Level Info -Message "=== START new-java-project-windows (Name=$Name BaseDir=$BaseDir) ==="

Ensure-Dir $BaseDir
$ProjectDir = Join-Path $BaseDir $Name
Ensure-Dir $ProjectDir

$existing = Get-ChildItem -LiteralPath $ProjectDir -Force -ErrorAction SilentlyContinue
if ($existing.Count -gt 0) {
  Write-Log -Level Warning -Message "Project dir exists and is not empty: $ProjectDir"
  Write-Log -Level Warning -Message "Idempotent mode: only missing files will be created (no overwrites)."
}

Ensure-Dir (Join-Path $ProjectDir "src")
Ensure-Dir (Join-Path $ProjectDir "scripts")
Ensure-Dir (Join-Path $ProjectDir "build")

$TemplateVersion = "1.0.0"
$CreatedAt = Get-ISTTimestamp

Write-IfMissing (Join-Path $ProjectDir ".gitignore") @"
build/
*.class
.DS_Store
"@

Write-IfMissing (Join-Path $ProjectDir "src\Main.java") @"
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello from $Name!");
    }
}
"@

Write-IfMissing (Join-Path $ProjectDir "scripts\build.ps1") @"
<#
Usage:
  powershell -File .\scripts\build.ps1
#>
if (-not (Test-Path -LiteralPath ".\build")) { New-Item -ItemType Directory -Path ".\build" -Force | Out-Null }
javac -d .\build .\src\Main.java
Write-Host "Build complete: build\Main.class"
"@

Write-IfMissing (Join-Path $ProjectDir "scripts\run.ps1") @"
<#
Usage:
  powershell -File .\scripts\run.ps1

Builds first, then runs.
#>
powershell -File .\scripts\build.ps1
java -cp .\build Main
"@

Write-IfMissing (Join-Path $ProjectDir "scripts\clean.ps1") @"
<#
Usage:
  powershell -File .\scripts\clean.ps1
#>
if (Test-Path -LiteralPath ".\build") { Remove-Item -LiteralPath ".\build" -Recurse -Force }
Write-Host "Cleaned build\"
"@

Write-IfMissing (Join-Path $ProjectDir "project_config.yaml") @"
project:
  name: "$Name"
  type: "java"
  created_at: "$CreatedAt"
  template_version: "$TemplateVersion"

java:
  toolchain: "openjdk"
  notes:
    - "This template uses javac/java directly (no Maven/Gradle)."
"@

Write-IfMissing (Join-Path $ProjectDir "README.md") @"
# $Name

This project was generated by **setup-aryan** on Windows.

## Quick Start (Windows)

```powershell
powershell -File .\scripts\run.ps1
````

## What got generated

* `project_config.yaml`: toolchain expectations
* `src\Main.java`: runnable entrypoint
* `scripts\build.ps1`, `scripts\run.ps1`, `scripts\clean.ps1`

## Requirements

* Java (JDK) installed and `javac` available on PATH
  "@

Save-State @{
status     = "ok"
project_dir= $ProjectDir
at         = (Get-ISTTimestamp)
}

Write-Log -Level Info -Message "=== DONE new-java-project-windows ==="
Write-Log -Level Info -Message "Project: $ProjectDir"
exit 0